---
title: "Week 3 Prac"
output: html_document
---

```{r}
library(sf)
library(here)
st_layers(here("gadm41_AUS.gpkg"))
```
```{r}
library(sf)
Ausoutline <- st_read(here("gadm41_AUS.gpkg"),
                      layer='ADM_ADM_0')
#read in the GeoPackage layer for the whole of Australia (layer ending in 0)
```
```{r}
#check the coordinate reference systems of sf or sp objects using the print function 
print(Ausoutline)
```
CRS= Coordinate Reference System 
3.5.1.3 Proj4
```{r}
#proj4 string tells the computer where on earth to locate the coordinates
library(sf)
st_crs(Ausoutline)$proj4string
#A proj4 string is meant to be a compact way of identifying a coordinate reference system
```
3.5.1.4 EPSG
```{r}
#set.. ALWAYS USE THIS LAH
Ausoutline <- Ausoutline %>%
  st_set_crs(., 4326)
```
```{r}
#NAH TOO COMPLICATED: or more concisely.. only useful if theres no CRS when you load the data 
Ausoutline <- st_read(here("gadm41_AUS.gpkg"),
                      layer='ADM_ADM_0') %>% 
  st_set_crs(4326)
```
3.5.1.5 Reprojecting your spatial data
```{r}
AusoutlinePROJECTED <- Ausoutline %>%
  st_transform(.,3112)
#use st_transform to reproject
print(AusoutlinePROJECTED)
```

```{r}
#From sf to sp
AusoutlineSP <- Ausoutline %>%
  as(.,"Spatial")

#From sp to sf
AusoutlineSF <- AusoutlineSP %>%
  st_as_sf()
#store as simple function
```
###3.5.2
```{r}
library(raster)
library(terra)
jan<-terra::rast(here("prac3_data", "wc2.1_5m_tavg", "wc2.1_5m_tavg_01.tif"))
# have a look at the raster layer jan
jan
```
```{r}
plot(jan)
```
```{r}
# set the proj 4 to a new object, project it as a Mollweide projection
pr1 <- terra::project(jan,"+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs")
plot(pr1)
```
```{r}
#to WGS84
pr1 <- pr1 %>%
  terra::project(.,"+proj=longlat +datum=WGS84 +no_defs +type=crs")
plot(pr1)
```
##3.5.3 Data Loading 
```{r}
#look in our folder, find the files that end with .tif and
library(fs)

dir_info("prac3_data/")
```
```{r}
#
library(tidyverse)
listfiles<-dir_info("prac3_data/") %>%
  filter(str_detect(path, ".tif")) %>%
  dplyr::select(path) %>%
  pull()

listfiles 
```
```{r}
#SpatRaster is a cllection of raster layers with the same spatial extent and resolution 
worldclimtemp <- listfiles %>%
  terra::rast()

#have a look at thr raster stack
worldclimtemp
```
```{r}
# access the january layer
worldclimtemp[[1]]
```
```{r}
#simple logic
month <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

names(worldclimtemp) <- month
```
```{r}
worldclimtemp$Jan
```
3.5.4 Raster Location 
```{r}
site <- c("Brisbane", "Melbourne", "Perth", "Sydney", "Broome", "Darwin", "Orange", 
          "Bunbury", "Cairns", "Adelaide", "Gold Coast", "Canberra", "Newcastle", 
          "Wollongong", "Logan City" )
lon <- c(153.03, 144.96, 115.86, 151.21, 122.23, 130.84, 149.10, 115.64, 145.77, 
         138.6, 153.43, 149.13, 151.78, 150.89, 153.12)
lat <- c(-27.47, -37.91, -31.95, -33.87, 17.96, -12.46, -33.28, -33.33, -16.92, 
         -34.93, -28, -35.28, -32.93, -34.42, -27.64)
#Put all of this information into one list
samples <- data.frame(site, lon, lat, row.names = "site")
#extract the data from the rasterstack for all points
AUcitytemp<- terra::extract(worldclimtemp, samples)
```

```{r}
AUcitytemp2 <- AUcitytemp %>%
  as_tibble()%>%
  add_column(Site = site, .before = "Jan")
```

#3.6 Part 2 Descriptive statistics
3.6.1Data Preparation
```{r}
Perthtemp <- AUcitytemp2 %>%
  filter(site=="Perth")
```
3.6.2 Histogram 
```{r}
hist(as.numeric(Perthtemp))
```
```{r}
library(tidyverse)
#define where you want to breaks in the histogram
userbreak<-c(8,10,12,14,16,18,20,22,24,26)

#remove the ID and site columns
Perthtemp <- AUcitytemp2 %>%
  filter(site=="Perth")

t<-Perthtemp %>%
  dplyr::select(Jan:Dec)

  hist((as.numeric(t)),
       breaks=userbreak,
       col="red",
       main="Histogram of Perth Temperature",
       xlab="Temperature",
       ylab="Frequency")
 
    
```
```{r}
#Check out the histogram information R generated
histinfo <- as.numeric(t) %>%
  as.numeric()%>%
  hist(.)

histinfo
#breaks — the cut off points for the bins (or bars), we just specified these
#counts — the number of cells in each bin
#midpoints — the middle value for each bin
#density — the density of data per bin
```
#3.6.3 Using more data 
```{r}
#Check the layer by plotting the geometry
plot(Ausoutline$geom)
```
```{r}
AusoutSIMPLE <- Ausoutline %>%
  st_simplify(., dTolerance = 1000) %>%
  st_geometry() %>%
  plot()
```
```{r}
print(Ausoutline)
```
```{r}
crs(worldclimtemp)
```
```{r}

Austemp <- Ausoutline %>%
  terra::crop(worldclimtemp,.)
  #now crop our temp data to the extent 

#plot the output
plot(Austemp)
```
```{r}
exactAus<-terra::mask(Austemp, Ausoutline)
```
```{r}
#subset using the known location of the raster 
hist(exactAus[[3]], col="red", main ="March temperature")
```
3.6.4 Histogram with ggplot
```{r}
exactAusdf <- exactAus %>%
  as.data.frame()

library(ggplot2)
#set up basic histogram
gghist <- ggplot(exactAusdf,
                 aes(x=Mar)) +
  geom_histogram(colour="black",
                 fill="white")+
  labs(title="Ggplot2 histogram of Australian March temperatures", 
       x="Temperature", 
       y="Frequency")
# add a vertical line to the hisogram showing mean tempearture
gghist + geom_vline(aes(xintercept=mean(Mar, 
                                        na.rm=TRUE)),
#dashline for Mean 
            color="blue", 
            linetype="dashed", 
            size=1)+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
squishdata<-exactAusdf%>%
  pivot_longer(
    #put our variable (months) into a one column using
  col = 1:12,
  names_to = "Month",
  values_to = "Temp"
  )
  
```
```{r}
#then subset the data

twomonths <- squishdata %>%
  # | = OR
  filter(., Month=="Jan" | Month=="Jun")
```

```{r}
#Get the mean for each month we selected, remember group_by() and summarise()
meantwomonths <- twomonths %>%
  group_by(Month) %>%
  summarise(mean=mean(Temp, na.rm=TRUE))

meantwomonths
```
```{r}
ggplot(twomonths, aes(x=Temp, color=Month, fill=Month)) +
  geom_histogram(position="identity", alpha=0.5)+
  geom_vline(data=meantwomonths, 
             aes(xintercept=mean, 
                 color=Month),
             linetype="dashed")+
  labs(title="Ggplot2 histogram of Australian Jan and Jun
       temperatures",
       x="Temperature",
       y="Frequency")+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
data_complete_cases <- squishdata %>%
  drop_na()%>% 
  mutate(Month = factor(Month, levels = c("Jan","Feb","Mar",
                                          "Apr","May","Jun",
                                          "Jul","Aug","Sep",
                                          "Oct","Nov","Dec")))

# Plot faceted histogram
ggplot(data_complete_cases, aes(x=Temp, na.rm=TRUE))+
  geom_histogram(color="black", binwidth = 5)+
  labs(title="Ggplot2 faceted histogram of Australian temperatures", 
       x="Temperature",
       y="Frequency")+
  facet_grid(Month ~ .)+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
library(plotly)
# split the data for plotly based on month

jan <- squishdata %>%
  drop_na() %>%
  filter(., Month=="Jan")

jun <- squishdata %>%
  drop_na() %>%
  filter(., Month=="Jun")

# give axis titles
x <- list (title = "Temperature")
y <- list (title = "Frequency")

# set the bin width
xbinsno<-list(start=0, end=40, size = 2.5)

# plot the histogram calling all the variables we just set
ihist<-plot_ly(alpha = 0.6) %>%
        add_histogram(x = jan$Temp,
        xbins=xbinsno, name="January") %>%
        add_histogram(x = jun$Temp,
        xbins=xbinsno, name="June") %>% 
        layout(barmode = "overlay", xaxis=x, yaxis=y)

ihist
```
```{r}
# mean per month
meanofall <- squishdata %>%
  group_by(Month) %>%
  summarise(mean = mean(Temp, na.rm=TRUE))

# print the top 1
head(meanofall, n=1)
```
```{r}
library(plotly)
# split the data for plotly based on month

jan <- squishdata %>%
  drop_na() %>%
  filter(., Month=="Jan")

jun <- squishdata %>%
  drop_na() %>%
  filter(., Month=="Jun")

# give axis titles
x <- list (title = "Temperature")
y <- list (title = "Frequency")

# set the bin width
xbinsno<-list(start=0, end=40, size = 2.5)

# plot the histogram calling all the variables we just set
ihist<-plot_ly(alpha = 0.6) %>%
        add_histogram(x = jan$Temp,
        xbins=xbinsno, name="January") %>%
        add_histogram(x = jun$Temp,
        xbins=xbinsno, name="June") %>% 
        layout(barmode = "overlay", xaxis=x, yaxis=y)

ihist

# mean per month
meanofall <- squishdata %>%
  group_by(Month) %>%
  summarise(mean = mean(Temp, na.rm=TRUE))

# standard deviation per month
sdofall <- squishdata %>%
  group_by(Month) %>%
  summarize(sd = sd(Temp, na.rm=TRUE))

# maximum per month
maxofall <- squishdata %>%
  group_by(Month) %>%
  summarize(max = max(Temp, na.rm=TRUE))

# minimum per month
minofall <- squishdata %>%
  group_by(Month) %>%
  summarize(min = min(Temp, na.rm=TRUE))

# Interquartlie range per month
IQRofall <- squishdata %>%
  group_by(Month) %>%
  summarize(IQR = IQR(Temp, na.rm=TRUE))

# perhaps you want to store multiple outputs in one list..
lotsofstats <- squishdata %>%
  group_by(Month) %>%
  summarize(IQR = IQR(Temp, na.rm=TRUE), 
            max=max(Temp, na.rm=T))

# or you want to know the mean (or some other stat) 
#for the whole year as opposed to each month...

meanwholeyear=squishdata %>%
  summarize(meanyear = mean(Temp, na.rm=TRUE))
```


          

